// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9rMzCf1jJLP5S-bF79KsEPOPq_yvLw8',
    appId: '1:1045791792298:web:422fc8fed9f9e3c47c04d3',
    messagingSenderId: '1045791792298',
    projectId: 'pipo-ea3fc',
    authDomain: 'pipo-ea3fc.firebaseapp.com',
    storageBucket: 'pipo-ea3fc.firebasestorage.app',
    measurementId: 'G-F68VW3WK04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdIy2YKjB1dasXOOn6qG9QqZWBOdmn0so',
    appId: '1:1045791792298:android:bdee6725ae14eb547c04d3',
    messagingSenderId: '1045791792298',
    projectId: 'pipo-ea3fc',
    storageBucket: 'pipo-ea3fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XYB7Jw4PngMgTvmxYwUVFChIXRkN698',
    appId: '1:1045791792298:ios:e7a0c067319c11bf7c04d3',
    messagingSenderId: '1045791792298',
    projectId: 'pipo-ea3fc',
    storageBucket: 'pipo-ea3fc.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2XYB7Jw4PngMgTvmxYwUVFChIXRkN698',
    appId: '1:1045791792298:ios:e7a0c067319c11bf7c04d3',
    messagingSenderId: '1045791792298',
    projectId: 'pipo-ea3fc',
    storageBucket: 'pipo-ea3fc.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu9rMzCf1jJLP5S-bF79KsEPOPq_yvLw8',
    appId: '1:1045791792298:web:35d7e7a853062e907c04d3',
    messagingSenderId: '1045791792298',
    projectId: 'pipo-ea3fc',
    authDomain: 'pipo-ea3fc.firebaseapp.com',
    storageBucket: 'pipo-ea3fc.firebasestorage.app',
    measurementId: 'G-7DFGQ7E338',
  );

}