// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzczndLtkNK5BQVyJG-rT_Y4ZzQ5BgP8M',
    appId: '1:701733039580:web:f147824ba1320a6ead7319',
    messagingSenderId: '701733039580',
    projectId: 'balz2-83929',
    authDomain: 'balz2-83929.firebaseapp.com',
    storageBucket: 'balz2-83929.firebasestorage.app',
    measurementId: 'G-GYEN43TW26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGj301-nMzDhgiBF-a0zLPjuaYnAferOs',
    appId: '1:701733039580:android:2ede431fc6ab327ead7319',
    messagingSenderId: '701733039580',
    projectId: 'balz2-83929',
    storageBucket: 'balz2-83929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByRUPrz0sKqD8XilEcFxbDpBbIjzAum_k',
    appId: '1:701733039580:ios:61b5c935a0a02caaad7319',
    messagingSenderId: '701733039580',
    projectId: 'balz2-83929',
    storageBucket: 'balz2-83929.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByRUPrz0sKqD8XilEcFxbDpBbIjzAum_k',
    appId: '1:701733039580:ios:61b5c935a0a02caaad7319',
    messagingSenderId: '701733039580',
    projectId: 'balz2-83929',
    storageBucket: 'balz2-83929.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzczndLtkNK5BQVyJG-rT_Y4ZzQ5BgP8M',
    appId: '1:701733039580:web:213f97a4a32e15e5ad7319',
    messagingSenderId: '701733039580',
    projectId: 'balz2-83929',
    authDomain: 'balz2-83929.firebaseapp.com',
    storageBucket: 'balz2-83929.firebasestorage.app',
    measurementId: 'G-9EV7BMR1JX',
  );

}