// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9vmBeflCjDz51s3wFxlr7icktvNhBWg',
    appId: '1:600721929451:web:6cb25ad910c19c812d3aae',
    messagingSenderId: '600721929451',
    projectId: 'innobeweeglab-main',
    authDomain: 'innobeweeglab-main.firebaseapp.com',
    databaseURL: 'https://innobeweeglab-main-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'innobeweeglab-main.firebasestorage.app',
    measurementId: 'G-8VDPJ549T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43rHHmDdHGZ7bgqd39ZXVhzl2LeDb3jc',
    appId: '1:600721929451:android:6f8e254def36fb482d3aae',
    messagingSenderId: '600721929451',
    projectId: 'innobeweeglab-main',
    databaseURL: 'https://innobeweeglab-main-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'innobeweeglab-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYAM2LNgTehu0Qo5K5JLZ3njbmQaa1QEE',
    appId: '1:600721929451:ios:dca5c52692416cf52d3aae',
    messagingSenderId: '600721929451',
    projectId: 'innobeweeglab-main',
    databaseURL: 'https://innobeweeglab-main-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'innobeweeglab-main.firebasestorage.app',
    iosClientId: '600721929451-up79r5n18eetp6nkbl95k10uadk9hqp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYAM2LNgTehu0Qo5K5JLZ3njbmQaa1QEE',
    appId: '1:600721929451:ios:dca5c52692416cf52d3aae',
    messagingSenderId: '600721929451',
    projectId: 'innobeweeglab-main',
    databaseURL: 'https://innobeweeglab-main-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'innobeweeglab-main.firebasestorage.app',
    iosClientId: '600721929451-up79r5n18eetp6nkbl95k10uadk9hqp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9vmBeflCjDz51s3wFxlr7icktvNhBWg',
    appId: '1:600721929451:web:7fecd863476680b82d3aae',
    messagingSenderId: '600721929451',
    projectId: 'innobeweeglab-main',
    authDomain: 'innobeweeglab-main.firebaseapp.com',
    databaseURL: 'https://innobeweeglab-main-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'innobeweeglab-main.firebasestorage.app',
    measurementId: 'G-WEX4SKHVGR',
  );
}
